object Form2: TForm2
  Left = 0
  Top = 0
  Caption = 'Form2'
  ClientHeight = 299
  ClientWidth = 635
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object UCaptionBar1: TUCaptionBar
    Left = 0
    Top = 0
    Width = 635
    Caption = '                    Caption bar'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWhite
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 0
    UseSystemCaptionColor = True
  end
  object panelRibbon: TUScrollBox
    Left = 0
    Top = 32
    Width = 635
    Height = 60
    HorzScrollBar.Tracking = True
    VertScrollBar.Tracking = True
    Align = alTop
    Color = 3355443
    ParentColor = False
    TabOrder = 1
    StyleElements = []
    AniSet.AniKind = akOut
    AniSet.AniFunctionKind = afkQuartic
    AniSet.DelayStartTime = 0
    AniSet.Duration = 120
    AniSet.Step = 6
    AniSet.Queue = True
    BackColor.Enabled = True
    BackColor.Color = clBlack
    BackColor.LightColor = 14342874
    BackColor.DarkColor = 3355443
    ScrollOrientation = oHorizontal
    ExplicitLeft = -170
    ExplicitWidth = 805
  end
  object Panel1: TPanel
    Left = 72
    Top = 160
    Width = 185
    Height = 41
    Caption = 'Panel1'
    TabOrder = 2
  end
end
