unit UCL.Colors;

interface

uses
  Graphics;

var
  MINI_SB_COLOR_NIL,
  MINI_SB_COLOR_LIGHT,
  MINI_SB_COLOR_DARK,
  SCROLLBOX_BACK_NIL,
  SCROLLBOX_BACK_LIGHT,
  SCROLLBOX_BACK_DARK: TColor;

implementation

initialization
  MINI_SB_COLOR_NIL   := $1A1A1A;
  MINI_SB_COLOR_LIGHT := $1A1A1A;
  MINI_SB_COLOR_DARK  := $7A7A7A;

  SCROLLBOX_BACK_NIL   := $E6E6E6;
  SCROLLBOX_BACK_LIGHT := $E6E6E6;
  SCROLLBOX_BACK_DARK  := $1F1F1F;

end.
